codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 2%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
